# install updates

- name: start wuauserv
  win_service:
    name: wuauserv
    state: started

- name: search for Windows updates 
  win_updates:
    state: searched
  register: update_search_result

- name: reboot, if needed
  win_reboot:
    pre_reboot_delay: 300
    reboot_timeout: 6000
  when: update_search_result.reboot_required

- name: Install-WindowsUpdate
  win_command: powershell.exe -ExecutionPolicy Bypass -NoProfile -Command 'Install-WindowsUpdate -NotCategory "Drivers" -NotTitle "OneDrive" -MicrosoftUpdate -AcceptAll -AutoReboot'

- name: wait for system to become reachable over WinRM
  wait_for_connection:
    delay: 60
    sleep: 15
    timeout: 900