# install updates

- name: wait for system to become reachable over WinRM
  wait_for_connection:
    delay: 60
    sleep: 15
    timeout: 1200

- name: search for Windows updates 
  win_updates:
    state: searched
  register: update_search_result

- name: reboot, if needed
  win_reboot:
    pre_reboot_delay: 60
    reboot_timeout: 600
  when: update_search_result.reboot_required

- name: Install-WindowsUpdate
  win_shell: |
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted -Force
    Install-WindowsUpdate -NotCategory "Drivers" -NotTitle "OneDrive" -MicrosoftUpdate -AcceptAll -IgnoreReboot
  become: yes

- name: search for Windows updates 
  win_updates:
    state: searched
  register: update_search_result

- name: reboot, if needed
  win_reboot:
    pre_reboot_delay: 60
    reboot_timeout: 600
  when: update_search_result.reboot_required