# install updates

- name: Install-WindowsUpdate
  win_shell: |
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted -Force
    Install-WindowsUpdate -NotCategory "Drivers" -NotTitle "OneDrive" -MicrosoftUpdate -AcceptAll -AutoReboot
  become: yes

- name: wait for system to become reachable over WinRM
  wait_for_connection:
    delay: 60
    sleep: 15
    timeout: 900