- hosts: all

  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_connection_timeout: 1000 
    ansible_winrm_operation_timeout_sec: 1000 
    ansible_winrm_read_timeout_sec: 1000

  tasks:

  - name: ping
    win_ping:

#  - include: QemuGuestAgent.yml

  - include: InstallUpdates.yml
  - include: InstallUpdates.yml

  - include: SMB1.yml
  - include: ConsumerFeatures.yml

  - include: Desktop.yml
  - include: LayoutModification.yml
  
  - include: OneDrive.yml
  - include: Remove-AppxPackage.yml

  - include: Chocolatey.yml
