- hosts: all

  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_connection_timeout: 1000 
    ansible_winrm_operation_timeout_sec: 1000 
    ansible_winrm_read_timeout_sec: 1000

    ansible_become_method: runas
    ansible_become_flags: logon_type=batch
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_password: "{{ ansible_password }}"

  tasks:

  - name: ping
    win_ping:

  - include: QemuGuestAgent.yml

  - include: Chocolatey.yml

  - include: InstallUpdates.yml
  - include: InstallUpdates.yml

  - include: SMB1.yml
  - include: ConsumerFeatures.yml

  - include: Desktop.yml
  - include: LayoutModification.yml

  - include: OneDrive.yml
  - include: Remove-AppxPackage.yml
